import type { NextPage } from "next";
import Head from "next/head";
import NavBar from "../components/NavBar";
import ReviewCard from "../components/ReviewCard";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>title of page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="p-5">
        <NavBar />
      </nav>
      <main className="m-2">
        <section id="welcome" className="flex p-5 justify-evenly">
          <h1 className="text-5xl font-black">
            Join the <br /> Training Squad <br /> and win prices{" "}
          </h1>
          <img src="" alt="" />
        </section>
        <section id="what" className="ml-20 mr-20">
          <h2 className="text-3xl mb-1">What we do ?</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Temporibus
            commodi quas ipsum modi enim pariatur fugiat iusto deserunt veniam
            mollitia, possimus error inventore nam praesentium dolorum doloribus
            sunt neque minima.
          </p>
        </section>
        <section id="review" className="ml-20 mr-20 mt-5">
          <h2 className="text-2xl mb-1">Hear from Community Members</h2>
          <div className="flex justify-center">
            <ReviewCard
              name="Name"
              image="https://i.pravatar.cc/300"
              review="Must join community da yebba !"
            />
            <ReviewCard
              name="Name"
              image="https://i.pravatar.cc/300"
              review="Must join community da yebba !"
            />
            <ReviewCard
              name="Name"
              image="https://i.pravatar.cc/300"
              review="Must join community da yebba !"
            />
          </div>
        </section>
      </main>
      <footer className="w-full"></footer>
    </div>
  );
};

export default Home;
